apiVersion: resourcetrees.krateo.io/v1
kind: CompositionReference
metadata:
  name: fireworksapp-demolive
  namespace: resource-tree-test
spec:
  filters:
    exclude:
    - apiVersion: "templates.krateo.io/v1alpha1"
      resource: "collections"
    - apiVersion: "templates.krateo.io/v1alpha1"
      resource: "widgets"
    - apiVersion: "v1"
      resource: "configmaps"
      name: "^composition-"
  reference:
    apiVersion: composition.krateo.io/v1-1-3
    name: demolive
    namespace: fireworksapp-system
    resource: fireworksapps