# permissions for end users to edit compositionreferences.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: compositionreference-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: composition-watcher
    app.kubernetes.io/part-of: composition-watcher
    app.kubernetes.io/managed-by: kustomize
  name: compositionreference-editor-role
rules:
- apiGroups:
  - resourcetrees.krateo.io
  resources:
  - compositionreferences
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resourcetrees.krateo.io
  resources:
  - compositionreferences/status
  verbs:
  - get
