# permissions for end users to view compositionreferences.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: compositionreferences-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: composition-watcher
    app.kubernetes.io/part-of: composition-watcher
    app.kubernetes.io/managed-by: kustomize
  name: compositionreferences-viewer-role
rules:
- apiGroups:
  - resourcetrees.krateo.io
  resources:
  - compositionreferencess
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resourcetrees.krateo.io
  resources:
  - compositionreferencess/status
  verbs:
  - get
